@startuml soluzione-diagramma

rectangle "Soluzione" as Soluzione {
  component OrderEntry
  component Logistics
  component PizzaFactoryLocator
  component OrderSubmit
  component Routing
  component InventoryManagement

  OrderEntry <--> Logistics
  OrderEntry --> PizzaFactoryLocator
  Logistics <--> OrderSubmit
  Logistics <--> Routing
  Logistics <--> InventoryManagement
}

@enduml